Repository GRTLCollaboration/GRTeclyn, pull requests merged in 2025-01, with the labels that each got.

#81 CI: Add missing CUDA and ROCm dependencies
  .github/workflows/gpu-build.yml
Labels: bug, devops

#82 Build: Remove default `TMP_BUILD_DIR`
  README.md
  Tools/GNUMake/Make.defaults
Labels: enhancement

#79 Add missing `Gpu::streamSynchronizes`
  Examples/BinaryBH/BinaryBHLevel.cpp
  Source/GRTeclynCore/GRAMRLevel.cpp
Labels: bug

#83 CI: Add Ccache to builds to speed them up
  .github/workflows/gpu-build.yml
  .github/workflows/regression-tests.yml
  .github/workflows/unit-tests.yml
Labels: enhancement, devops

#85 Port fixed grids tagging
  Source/TaggingCriteria/FixedGridsTaggingCriterion.hpp
Labels: enhancement
